In [5]:
import numpy as np

In [16]:
from numpy.core.fromnumeric import shape
print("Showing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}\nAverage: {}\nMax index: {}".format(np.max(b), np.average(b), np.argmax(b)))

print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))

print("\nUse numpy to create a [x,y] dimension array with random numbers")
def createRandomArray(x, y):
  return np.random.rand(x, y)
c = createRandomArray(3,3)
print("[3x3] random number array:\n{}".format(c))

print("\nDimension of previosly defined arrays.\na: {}\nb: {}\nc: {}".format(a.shape, b.shape, c.shape))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2

You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int64'>

Use numpy to create a [x,y] dimension array with random numbers
[3x3] random number array:
[[0.49203032 0.84227433 0.47108687]
 [0.15529708 0.34505623 0.43060535]
 [0.81308061 0.96563969 0.41234767]]

Dimension of previosly defined arrays.
a: (3,)
b: (5,)
c: (3, 3)


In [6]:
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print("Index: {}, was {}".format(i,e))



Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was Hello
Index: 1, was World
Index: 2, was !
